version: '3'

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_cityxa
      POSTGRES_USER: userdb_cityxa
      POSTGRES_PASSWORD: sodi
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  db_data: