# Generated by Django 4.1.7 on 2023-03-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_description'),
        ('users', '0005_alter_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='properties',
            field=models.ManyToManyField(blank=True, to='property.property'),
        ),
    ]
