# Generated by Django 3.1.7 on 2023-02-18 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rent_buy', models.PositiveSmallIntegerField(choices=[(1, 'Rent'), (2, 'Buy')], default=1)),
                ('price', models.IntegerField()),
                ('num_rooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('furniture', models.BooleanField(blank=True, null=True)),
                ('build_year', models.DateField(blank=True, null=True)),
                ('elevator', models.BooleanField(blank=True, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, null=True)),
                ('balcony', models.BooleanField(blank=True, null=True)),
                ('renovated', models.BooleanField(blank=True, null=True)),
                ('storage', models.BooleanField(blank=True, null=True)),
                ('disable_access', models.BooleanField(blank=True, null=True)),
                ('safe_room', models.BooleanField(blank=True, null=True)),
                ('central_air_conditioner', models.BooleanField(blank=True, null=True)),
                ('quiet_neighborhood', models.BooleanField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.adress')),
                ('owner', models.ForeignKey(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
