# Generated by Django 3.1.7 on 2023-02-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='clicked_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='id_type_of_property',
            field=models.PositiveSmallIntegerField(choices=[(1, 'appartment'), (2, 'villa'), (3, 'duplex'), (4, 'floor-appartment'), (5, 'vacation Apartment'), (6, 'basement floor'), (7, 'studio/loft'), (8, 'roof/penthouse'), (9, 'office')], default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=users.models.User, on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(default='images/home_default.png', to='property.ImageDescription'),
        ),
    ]
