# Generated by Django 3.1.7 on 2023-02-20 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20230220_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='build_year',
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
