# Generated by Django 3.1.7 on 2023-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230227_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos'),
        ),
    ]
