# Generated by Django 4.1.7 on 2023-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_imagedescription_image_alter_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='city',
        ),
        migrations.AlterField(
            model_name='imagedescription',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\so16s\\PycharmProjects\\Cityxa\\src\\mediafiles/property_photos/home_default.png', null=True, upload_to='property_photos'),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(default='C:\\Users\\so16s\\PycharmProjects\\Cityxa\\src\\mediafiles/property_photos/home_default.png', to='property.imagedescription'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
