# Generated by Django 4.1.7 on 2023-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_street_city_alter_imagedescription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedescription',
            name='image',
            field=models.ImageField(default='C:\\Users\\so16s\\PycharmProjects\\Cityxa\\src\\mediafiles/property_photos/home_default.png', upload_to='property_photos'),
        ),
    ]
